### ISSUE TITLE
Paging in search result

### ISSUE THREAD

**Issue by nielsklazenga** [AtlasOfLivingAustralia/avh-hub#59] opened 2016-07-06 01:09 UTC
There have been a few emails about this, but I haven't seen an issue.

When paging through the search results in AVH you go to the **Map** tab instead of staying in the **Records** tab. The '#tab_mapView' anchor is added to the URL every time.

**Comment by ben3000** [comment] 2016-09-13 08:29
Duplicate of #35.

**Closed** 2016-09-13 08:29 UTC
Labels: duplicate
