### ISSUE TITLE
'Colour by' option fails to load map legend (for particular browsers)

### ISSUE THREAD

**Issue by kylie-m** [AtlasOfLivingAustralia/avh-hub#145] opened 2023-11-23 23:07 UTC
On AVH, in the map view of results, the use of 'Colour by' results in the map legend failing to load. (screenshots below)

- It seems to be happening for all 'Colour by' options.
- This appears to function using Chrome (only for some users), but not Firefox, Safari, or Edge. 
- It also works on the ALA interface, so there is a workaround for users. 

Example: 
1. Search for a genus name (e.g. Najas)
2. On the map results tab, choose to 'Colour by' scientific name
3. Check if the legend (right-hand side) loads. It should show a list of species and the various colours displayed on the map, (and users should be able to de-select particular species, removing them from map view). Instead, a message is displayed: “Loading legend….”.
 
Screenshot 1: not working
<img width="1718" alt="Screenshot 2023-11-24 at 10 03 38 am" src="https://github.com/AtlasOfLivingAustralia/avh-hub/assets/90439797/89b5d7f4-1101-4eb3-822d-4c1f62f64563">

Screenshot 2: working
<img width="1425" alt="Screenshot 2023-11-24 at 10 05 18 am" src="https://github.com/AtlasOfLivingAustralia/avh-hub/assets/90439797/8b0ca6c4-331c-4024-8e88-22c24bddcc2c">

**Comment by kylie-m** [comment] 2023-11-23 23:08
Reported by user https://support.ehelp.edu.au/a/tickets/190147

**Comment by timhicks-ala** [comment] 2023-11-30 21:41
Also reported in:
https://support.ehelp.edu.au/a/tickets/186308
https://support.ehelp.edu.au/a/tickets/187975

**Comment by adam-collins** [comment] 2024-02-06 03:53
Can I get another example of failure please. I cannot reproduce with the given example or with some general use. There has been one biocache-service release since this issue was raised. There has been no change to the API Gateway since this issue was raised.

**Comment by adam-collins** [comment] 2024-02-07 00:37
Fixed in test. The problem occurs when you are not logged in. ozcam-hub had the same problem.

**Comment by timhicks-ala** [comment] 2024-02-07 00:43
@adam-collins good catch. Logging in is a trivial work-around too, I'll communicate that out to the reporting users.

**Closed** 2024-04-19 00:44 UTC
